# Default
metric: accuracy

# Losses
loss_fn: mse

# Training
batch_size: 2
use_old_method: false

# Model
model_kwargs:
  activation_fn: relu
  dropout_prob: 0.0
  input_dim: 2
  output_dim: 5

# Git
branch: main
commit: bdc3aed
